"""Generate relocation-aware reference patterns from the two audited captures.

Only address operands explicitly decoded by MSVC dumpbin may vary. Opcodes,
field offsets, constants, internal branches and virtual-call slots stay exact.
External targets must resolve to the same Address Library identity + addend.
This is not proof that uncaptured runtimes match these instruction templates.
"""
import importlib.util
import hashlib
import json
from pathlib import Path
import re
import struct
import sys

ROOT = Path(__file__).resolve().parents[1]
SLEEP_IMPORT = 0xFFFFFFFFFFFFFFFF
def module(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    result = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(result)
    return result
ownership = module('ownership', Path(__file__).with_name('check-native-addon-ownership.py'))
mapping = module('mapping', Path(__file__).with_name('audit-addon-version-map.py'))

def import_slots(path):
    pe = mapping.audit.audit.PE(path.read_bytes())
    optional = pe.u32(0x3C) + 24
    imports = pe.u32(optional+112+8)
    result = {}
    def string(rva):
        start = pe.raw(rva)
        return pe.data[start:pe.data.index(b'\0',start)].decode('ascii')
    for index in range(256):
        offset = pe.raw(imports+index*20)
        lookup, _, _, name, address = struct.unpack_from('<IIIII',pe.data,offset)
        if not name: break
        dll = string(name).lower()
        for item in range(16384):
            value = struct.unpack_from('<Q',pe.data,pe.raw(lookup+item*8))[0]
            if not value: break
            if value & (1<<63): continue
            result[address+item*8] = (dll,string(value+2))
    return result

def generate():
    code = ['// Generated by tools/generate-addon-relocation-patterns.py. Do not hand-edit.',
            '#pragma once', '#include "BodyChangeNG/RelocatedCodePattern.h"',
            'namespace bcn::native_addon::patterns {']
    evidence = []
    for branch, root, file in [('se', mapping.ROOTS[0], 'version-1-5-97-0.bin'),
                                ('ae', mapping.ROOTS[1], 'versionlib-1-6-1170-0.bin')]:
        records = ownership.captures(branch)
        ownership.verify(branch, records)
        assert hashlib.sha256(Path(records[0]['exe']).read_bytes()).hexdigest() == records[0]['exeSha256']
        imports = import_slots(Path(records[0]['exe']))
        _, ids = mapping.audit.library(root/file)
        reverse = {rva: ident for ident,rva in ids.items()}
        sorted_rvas = sorted(reverse)
        instructions = {}
        for folder, record in zip(ownership.FOLDERS[branch], records):
            dump = (ROOT/'build/audits/addon-txst'/folder/'native-face-code.disasm.txt').read_text()
            for line in dump.splitlines():
                found = re.match(r'\s+([0-9A-F]{16}):\s+((?:[0-9A-F]{2}(?:\s+|$))+)(.*)', line)
                if found:
                    address, _, text = found.groups()
                    instructions[int(address,16)-record['imageBase']] = (text.strip(), record['imageBase'])
        source = (ROOT/'src/BodyChangeNG/NativeAddonRuntime.h').read_text()
        table = source.split(branch+'OwnershipCode{',1)[1].split('};',1)[0]
        pins = [(int(a,16),int(b,16)) for a,b in re.findall(r'CodeFingerprint\{\s*(0x[0-9A-F]+),\s*(0x[0-9A-F]+)',table)]
        objects = []
        for index,(rva,size) in enumerate(pins):
            ident = reverse[rva]
            data = next(bytes.fromhex(f['hex'])[rva-f['rva']:rva-f['rva']+size]
                        for r in records for f in r['functions'] if f['rva']<=rva and rva+size<=f['end'])
            offsets = sorted(a for a in instructions if rva<=a<rva+size)+[rva+size]
            assert offsets[0] == rva
            rels=[]
            for address,end in zip(offsets,offsets[1:]):
                text,image_base=instructions[address]
                target=re.search(r'\[([0-9A-F]{16})h\]|\b(?:call|j\w+)\s+([0-9A-F]{16})h?',text)
                if not target:
                    assert not any(image_base <= int(value,16) < image_base+0x10000000
                                   for value in re.findall(r'\b([0-9A-F]{16})h',text)), (branch,hex(address),text)
                    continue
                absolute=int(next(g for g in target.groups() if g),16)
                # All records of a branch have one executable image; obtain the
                # base of the actual disassembly owning this instruction.
                dest=absolute-image_base
                if rva<=dest<rva+size: continue
                raw=data[address-rva:end-rva]
                positions=[i for i in range(len(raw)-3) if end+struct.unpack_from('<i',raw,i)[0]==dest]
                assert len(positions)==1, (branch,hex(address),text,positions)
                nearest=max(a for a in sorted_rvas if a<=dest)
                # Never invent an identity for a distant unlabeled target.
                assert dest-nearest<0x1000, (hex(dest),hex(nearest))
                if imports.get(dest) == ('kernel32.dll','Sleep'):
                    rels.append((address-rva+positions[0],end-rva,SLEEP_IMPORT,0))
                else:
                    rels.append((address-rva+positions[0],end-rva,reverse[nearest],dest-nearest))
            name=f'{branch}{index}'
            code.append(f'inline constexpr char {name}Bytes[] =')
            for pos in range(0,len(data),32):
                code.append('    "'+''.join(f'\\x{b:02X}' for b in data[pos:pos+32])+'"')
            code[-1]+=';'
            code.append(f'inline constexpr RelativeOperand {name}Operands[] = {{')
            for pos,end,target,delta in rels:
                token = 'kSleepImport' if target == SLEEP_IMPORT else str(target)
                code.append(f'    {{ {pos}, {end}, {token}, 0x{delta:X} }},')
            # C++ disallows empty C arrays. Span {} in descriptor handles it.
            if rels: code.append('};')
            else: code.pop()
            operands=name+'Operands' if rels else '{}'
            objects.append(f'    {{ {ident}, std::string_view{{ {name}Bytes, sizeof({name}Bytes)-1 }}, {operands} }},')
            evidence.append(dict(branch=branch,id=ident,rva=rva,size=size,operands=rels))
        code.append(f'inline constexpr RelocatedPattern {branch}[] = {{')
        code+=objects+['};']
    code+=['}']
    return {'header':'\n'.join(code)+'\n','evidence':evidence}

if __name__ == '__main__':
    print(json.dumps(generate()))
